# Generated by Django 5.2.4 on 2026-02-26 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=10)),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(max_length=100)),
                ('design', models.CharField(max_length=100)),
                ('qtesortie_ancien', models.IntegerField(blank=True, null=True)),
                ('qtesortie_nouv', models.IntegerField(blank=True, null=True)),
                ('utilisateur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('numero_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('numero_produit', models.AutoField(primary_key=True, serialize=False)),
                ('design', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtesortie', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
